# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options

[profile.default]
src = "src"
out = "out"
libs = ["lib"]
test = "test"

remappings = [
    "forge-std/=./lib/forge-std/src/",
    "@openzeppelin/contracts=./lib/openzeppelin-contracts/contracts",
    '@account-abstraction/contracts=./lib/account-abstraction/contracts',
    "@layerzerolabs/contracts=./lib/layerzero-v2/packages/layerzero-v2/evm/oapp/contracts",
                         
]

[etherscan]
holesky = { key = "${ETHERSCAN_API_KEY}" }
amoy = { key = "${POLYGONSCAN_API_KEY}" }

[rpc_endpoints]
ethereum = "${ETHEREUM_RPC_URL}"
sepolia = "${SEPOLIA_RPC_URL}"
holesky= "${HOLESKY_RPC_URL}"
amoy = "${AMOY_RPC_URL}"
polygon = "${POLYGON_RPC_URL}"

