# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options

[profile.default]
src = "src"
out = "out"
libs = ["lib"]
test = "test"

remappings = [
    "@openzeppelin/contracts=./lib/openzeppelin-contracts",
    '@account-abstraction/contracts=./lib/@account-abstraction/contracts',
    "@layerzero-v2/evm=./lib/@layerzero-v2/evm/oapp"
]

[etherscan]
holesky = { key = "${ETHERSCAN_API_KEY}" }
amoy = { key = "${POLYGONSCAN_API_KEY}" }

[rpc_endpoints]
ethereum = "${ETHEREUM_RPC_URL}"
sepolia = "${SEPOLIA_RPC_URL}"
holesky= "${HOLESKY_RPC_URL}"
amoy = "${AMOY_RPC_URL}"
polygon = "${POLYGON_RPC_URL}"

