# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options

[profile.default]
src = "src"
out = "out"
libs = ["lib"]
test = ["test"]
solc-version = '0.8.09'


remappings = [
    # Due to a misconfiguration of solidity-bytes-utils, an outdated version
    # of forge-std is being dragged in
    # 
    # To remedy this, we'll remap the ds-test and forge-std imports to ou own versions
    'ds-test/=lib/@layerzerolabs/toolbox-foundry/lib/ds-test',
    'forge-std/=lib/@layerzerolabs/toolbox-foundry/lib/forge-std',
    '@layerzerolabs/=lib/@layerzerolabs/',
    '@openzeppelin/=lib/@openzeppelin/',
    '@openzeppelin/contracts=lib/openzeppelin-contracts/contracts',


]

[etherscan]
holesky = { key = "${ETHERSCAN_API_KEY}" }
amoy = { key = "${POLYGONSCAN_API_KEY}" }


[rpc_endpoints]
ethereum = "${ETHEREUM_RPC_URL}"
sepolia = "${SEPOLIA_RPC_URL}"
holesky= "${HOLESKY_RPC_URL}"
amoy = "${AMOY_RPC_URL}"
polygon = "${POLYGON_RPC_URL}"

